services:
  - type: web
    name: backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.cjs
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: web
    name: frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
